// https://webpack.js.org/contribute/plugin-patterns/#root
class MyPlugin {
  apply(compiler) {
    compiler.hooks.emit.tapAsync('MyPlugin', (compilation, callback) => {
      // Explore each chunk (build output):
      compilation.chunks.forEach(chunk => {
        // console.log('chunk: ', chunk);
        // Explore each module within the chunk (built inputs):
        chunk.getModules().forEach(module => {
          // console.log('module: ', module);
          // Explore each source file path that was included into the module:
          module.buildInfo && module.buildInfo.fileDependencies && module.buildInfo.fileDependencies.forEach(filepath => {
            // console.log('filepath: ', filepath);
            // we've learned a lot about the source structure now...
          });
        });

        // Explore each asset filename generated by the chunk:
        chunk.files.forEach(filename => {
          // Get the asset source for each file generated by the chunk:
          var source = compilation.assets[filename].source();
          // console.log('source: ', source);
        });
      });

      callback();
    });
  }
}

module.exports = MyPlugin;
